service: YapawaImages
frameworkVersion: ">=1.37.1 <2.0.0"

custom:
  stage: ${file(stages/${opt:stage, self:provider.stage}.yml)}
  domainName: ${self:custom.stage.domainName, ''}
  hostedZoneId: ${self:custom.stage.hostedZoneId, ''}
  certificateArn: ${self:custom.stage.certificateArn, ''}

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

plugins:
  - serverless-deployment-bucket
  - serverless-pseudo-parameters
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, self:custom.stage.region}
  profile: ${self:custom.stage.profile}
  memorySize: ${self:custom.stage.lambda.memorySize, '128'}
  timeout: ${self:custom.stage.lambda.timeout, '10'}
  logRetentionInDays: ${self:custom.stage.lambda.logRetention, '1'}
  iamRoleStatements: ${file(config/iamRoleStatements.yml)}
  deploymentBucket:
    name: com.serverless.${self:custom.stage.profile}.${self:provider.region}.deploys
  apiName: ${self:service}${self:custom.stage.suffix}
  httpApi:
    cors: true
    payload: '1.0'

functions: ${file(lib/config.js):functions}
resources:
  Resources: ${file(lib/config.js):resources}
  # Outputs: ${file(lib/config.js):outputs}
